print('Primeiro e último nome de uma pessoa')
print(20 * '-=')
nome = str(input('Digite o seu nome completo: ')).split()
print(f'Seu primeiro nome é: {nome[0]}')
print(f'Seu último nome é: {nome[-1]}')